#!/bin/bash
cd $(dirname $0)
TREE_TOP=../..
export LD_LIBRARY_PATH=$TREE_TOP/install_dir/lib
export LD_PRELOAD=/lib/x86_64-linux-gnu/libpthread.so.0

CMD="./exchange-tls12"
#CMD="gdb --args ./exchange-tls12"

# -c may specify many ciphers; just first available will be run
# :ECDH-ECDSA-AES128-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256
${CMD} \
 -c ":ECDHE-ECDSA-AES128-GCM-SHA256" \
 -p $TREE_TOP/certstore/trusted \
 -b $TREE_TOP/certstore/trusted/homut_bundle.crt \
 -f $TREE_TOP/certstore/personal/homut_client_eccx08.crt \
 -k $TREE_TOP/certstore/privkeys/homut_client_eccx08.key \
 -e ateccx08
